version: '3.8'

services:
  mbot:
    image: cianoid/mbot:latest
    restart: always
    volumes:
      - logs_value:/app/logs/
      - sqlite_value:/app/db/
    env_file:
      - ./.env

volumes:
  sqlite_value:
  logs_value:
