version: '3.8'

services:
  mbot:
    build: ../app/
    restart: always
    volumes:
      - logs_value:/app/logs/
      - sqlite_value:/app/db/
    env_file:
      - ../app/.env

volumes:
  sqlite_value:
  logs_value: