# .github/workflows/**bot_workflow.yml**
name: Foodgram main workflow

on: push

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r requirements.txt 

    - name: Test with flake8
      run: |
        cd ./app/
        python -m flake8

  send_message_after_tests:
    name: Send tg-message after tests-job
    runs-on: ubuntu-latest
    needs: [tests]
    if: always()

    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Задача tests ${{ github.workflow }} из репозитория ${{ github.repository }} выполнена
            
            Статусы задачи tests: ${{ needs.tests.result }}
